### ISSUE TITLE
Success with v2023.3, failure with v2024.4

### ISSUE THREAD

**Issue by 13k10t** [sys-fs/mullvad-repack#1]
Hello and thank you for the scripts! I managed to get Mullvad VPN working on Devuan Daedalus 5.0.1 using your repack, though I ran into two small issues:

1)  Executing `repack.sh` throws an invalid token syntax error on line 14, which is specifically `else;`. Removing the `;` solves this.

2) The latest version of Mullvad VPN (v2024.4) is not supported, and generating the patched .deb package for that version throws errors for `preinst.patch ` at `Hunk #1`. Downgrading to v2023.3 solves this.

3) While not really an issue, just wanted to point out that the last line of  `README.md` seems to cut off mid-sentence.

I’m overjoyed that the script did indeed generate a valid, working package for Mullvad VPN v2023.3, but I’m wondering if there’s any chance the script/patch package could be updated to work with the latest version of Mullvad VPN (v2024.4), or perhaps insight could be provided on what modifications could be done so that `mullvad-repack` might support future updates as well. I realize that comparing previous packages to new ones and modifying the patches for each release is probably not an insignificant task, and I’m happy to help if I can. I just don’t have much shell scripting experience, but I do take direction well and will be happy to pass the info along to others.

Thank you again for your time and efforts!

**Comment by sys-fs** [comment]
Hey, thanks for raising this. I'd have probably noticed this issue myself but I've been lazy with updating Mullvad. Glad these scripts are useful for you, and I will have a look at fixing them tomorrow. :-) I currently use sysvinit (like most Devuan users probably!), but I would assume that OpenRC would continue to work after updating the patch files.

**Comment by 13k10t** [comment]
Hey back and thanks for the quick reply! Yes, using sysvinit here as well and very happy to have found your repack worked on Daedalus when other methods failed (more likely the faults were between the screen and the chair here). Will be eager to test out an updated version if and when you find time, it definitely is appreciated and thanks again!

**Comment by sys-fs** [comment]
I've updated the patch files to work with the 2024.4 release and have installed the rebuilt package on my laptop. All seems good, though I had to reconnect to Mullvad afterwards. I use the daemon rather than the GUI app, so I'm not sure if that's just a daemon thing. Feel free to reopen if the updates don't work for you.

**Comment by 13k10t** [comment]
Awesome, works great - thanks so much again for your time and efforts!
